#
#!/bin/bash
#Script Menu utama
#
echo ""
echo "==============================================="
echo "MENU UTAMA | Senarai Pilihan Yang Tersedia"
echo "==============================================="
echo " 01      - Cipta Akaun Percubaan"
echo " 02   - Buat Akaun Pelanggan"
echo " 03   - Senarai Akaun Pelanggan"
echo " 04     - Senarai Akaun Aktif"
echo " Expired    - Butiran Akaun"
echo " Expand     - Tambah Tamat Tempoh Akaun"
echo " 05     - Melumpuhkan Multi Login"
echo " 06     - Memadam Akaun"
echo " Banner     - Moded Banner SSH"
echo " Speedtest  - VPS Speedtest"
echo " System     - Butiran System VPS"
echo " Restart    - Perkhidmatan OpenVPN, Dropbear, Webmin, Squid3"
echo " Reboot     - Rerunning VPS"
echo " About      - Butiran VPS"
echo "==============================================="
echo "DOCTYPE | Explore Network Unlimited"
echo "==============================================="
echo ""
